### ISSUE TITLE
Bug: 使用access token时存在 Cannot read properties of undefined (reading 'choices') 报错

### ISSUE THREAD

**Issue by huangwb8** [Kerwin1202/chatgpt-web#24]
发送消息时，前端界面出现如下报错：

```
Cannot read properties of undefined (reading 'choices')
```

日志如下：

```
token_chatgpt-app-1       | TypeError: Cannot read properties of undefined (reading 'choices')
token_chatgpt-app-1       |     at process (/app/build/index.js:10469:44)
token_chatgpt-app-1       |     at onProgress (/app/build/index.js:9961:9)
token_chatgpt-app-1       |     at onMessage (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:635:21)
token_chatgpt-app-1       |     at <anonymous> (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:62:7)
token_chatgpt-app-1       |     at parseEventStreamLine (/app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/src/parse.ts:125:17)
token_chatgpt-app-1       |     at Object.feed (/app/node_modules/.pnpm/eventsource-parser@1.0.0/node_modules/eventsource-parser/src/parse.ts:101:28)
token_chatgpt-app-1       |     at feed (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:84:12)
token_chatgpt-app-1       |     at fetchSSE (/app/node_modules/.pnpm/chatgpt@5.2.2/node_modules/chatgpt/build/index.js:100:7)
token_chatgpt-app-1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
token_chatgpt-app-1       | TypeError: Cannot read properties of undefined (reading 'usage')
token_chatgpt-app-1       |     at <anonymous> (/app/build/index.js:10508:30)
token_chatgpt-app-1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
token_chatgpt-database-1  | 2023-04-16T10:07:32.856+0000 I STORAGE  [conn3] createCollection: chatgpt.chat with generated UUID: 807d04cb-8448-400f-92df-5497f8f8732d
```

docker-compose.yml内容类似：

```
version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web:v2.12.1 # 总是使用latest,更新时重新pull该tag镜像即可
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      OPENAI_ACCESS_TOKEN: eyJh-xxx-cg
      API_REVERSE_PROXY: http://xxx:8080/conversation # 自建并经过他人验证的反代
      AUTH_SECRET_KEY: 8jxxx
      TIMEOUT_MS: 60000
      SITE_TITLE: TokenChat
      MONGODB_URL: 'mongodb://chatgpt:password01@database:27017'
      REGISTER_ENABLED: true
      REGISTER_MAILS: '@qq.com,@gmail.com,@163.com'
      PASSWORD_MD5_SALT: tNxxx
      ROOT_USER: xx@qq.com
      SITE_DOMAIN: https://xxx.com
      SMTP_HOST: smtp.qq.com
      SMTP_PORT: 465
      SMTP_TSL: true
      SMTP_USERNAME: xxx@qq.com
      SMTP_PASSWORD: xxx
    links:
      - database

  database:
    image: mongo:3.6
    restart: unless-stopped
    # ports:
    #  - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: password01
      MONGO_INITDB_DATABASE: chatgpt

  gui:
    image: mongo-express:1.0.0-alpha
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_BASICAUTH_USERNAME: a4xxx
      ME_CONFIG_BASICAUTH_PASSWORD: zzxxx
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: chatgpt
      ME_CONFIG_MONGODB_ADMINPASSWORD: password01
      ME_CONFIG_MONGODB_URL: 'mongodb://chatgpt:password01@database:27017'
```

日志的提示似乎是指token模式下没有找到`usage`这一collection (它只对API模式生效)。 是否是bug？
