### ISSUE TITLE
mongo-gui连接mongodb超时

### ISSUE THREAD

**Issue by DoNotSayYes** [Kerwin1202/chatgpt-web#279]
请教下大佬，我用的以下数据库配置，但是mongo-gui服务起不来，log提示连接超时，请问知道可能是什么原因吗？@Kerwin1202
```
> Failed to connect mongoDB - MongoTimeoutError: Server selection timed out after 30000 ms
> Connecting to mongoDB @ mongodb://chatgpt:admin123@chatgpt:27017
```

```
  database:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: chatgpt

  mongo-gui:
    container_name: mongo-gui
    image: ugleiton/mongo-gui
    container_name: mongo-ui
    restart: always
    ports:
      - '4321:4321'
    environment:
      - MONGO_URL=mongodb://chatgpt:admin123@chatgpt:27017
    links:
      - database
    depends_on:
      - database
```
