### ISSUE TITLE
最新镜像未开启注册功能，但被强制要求登录

### ISSUE THREAD

**Issue by UnknownErrorCodes** [Kerwin1202/chatgpt-web#31]
在REGISTER_ENABLED: false下创建docker容器（容器image日期：Apr 16, 2023 at 10:00 pm）
被强制要求登录，对话框输入框无法选中，发送按钮无法点击

**Comment by Kerwin1202** [comment]
REGISTER_ENABLED 是 是否开启注册 登录是  AUTH_SECRET_KEY

**Comment by UnknownErrorCodes** [comment]
> REGISTER_ENABLED 是 是否开启注册 登录是 AUTH_SECRET_KEY 不为空就要登录

version: '3'

```
services:
  app:
    image: kerwin1202/chatgpt-web:latest
    container_name: chatgptweb2
    restart: unless-stopped
    ports:
      - '127.0.0.1:3004:3002'
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      OPENAI_ACCESS_TOKEN: ''
      API_REVERSE_PROXY: 'http://172.23.0.2:3000/backend-api/conversation'
      MAX_REQUEST_PER_HOUR: 0
      TIMEOUT_MS: 60000
      SITE_TITLE: ChatGpt Web
      MONGODB_URL: 'mongodb://chatgpt2:xxxx2@database:27017'
      REGISTER_ENABLED: false
```
以上是我的docker-compose.yml启动部分内容，“REGISTER_ENABLED ”为false，并未定义“AUTH_SECRET_KEY ”
该文件在使用2.11.9版本的容器完全正常工作

**Comment by UnknownErrorCodes** [comment]
> REGISTER_ENABLED 是 是否开启注册 登录是 AUTH_SECRET_KEY 不为空就要登录

顺带一提，最新版本的镜像目前还是无法记录使用“OPENAI_ACCESS_TOKEN”下的ai回复

下图是我通过删除页面禁用属性，绕过强制要求登录后，进行对话并刷新页面后的结果

![无标题](https://user-images.githubusercontent.com/54696989/232319943-67abfac7-b515-4f09-8862-3595e57131c9.png)
这个在使用“OPENAI_ACCESS_TOKEN”不能记录ai回复的问题，在V2.11.9版本是没有的

**Comment by Kerwin1202** [comment]
@UnknownErrorCodes  AccessToken 有没有可能是你 代理的问题 我刚一直测试不回复消息

**Comment by UnknownErrorCodes** [comment]
> @UnknownErrorCodes AccessToken 有没有可能是你 代理的问题 我刚一直测试不回复消息

该代理是我用[node-chatgpt-proxy](https://github.com/ikechan8370/node-chatgpt-proxy)项目搭建的docker容器，没有对外，在V2.11.9版本测试正常，在最新版本镜像也可进行对话，但数据库没有存入ai的回复

**Comment by Kerwin1202** [comment]
我试了下 好像搭建并不行

`docker run -d -p 18080:3000 --name node-chatgpt-proxy --shm-size=1gb geyinchi/node-chatgpt-proxy`

**Comment by UnknownErrorCodes** [comment]
> 



> 我试了下 好像搭建并不行
> 
> `docker run -d -p 18080:3000 --name node-chatgpt-proxy --shm-size=1gb geyinchi/node-chatgpt-proxy`

我的搭建方法是编写docker-compose.yml建立node-chatgpt-proxy容器
然后通过`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' node-chatgpt-proxy-app-1`获取该容器ip地址
把该ip地址和合并成'http://172.23.0.2:3000/backend-api/conversation'后填入你这个项目中自己所写的docker-compose.yml，
并在docker-compose.yml里指定加入通过docker network ls所查到的node-chatgpt-proxy容器network名称

**Comment by UnknownErrorCodes** [comment]
再反馈一下，最新镜像ai回复不完整，如下图
![无标题2](https://user-images.githubusercontent.com/54696989/232321504-b541909e-c03a-4b15-8a15-070f498cba4c.png)
服务端报以下错误
```
TypeError: Cannot read properties of undefined (reading 'usage')
     at <anonymous> (/app/build/index.js:10569:30)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
该问题在2.11.9版本也不存在

**Comment by Kerwin1202** [comment]
也稍微改了下  下个版本试试吧。。。

至于没登录的 完整配置发下，隐藏下自己的信息。。 另外其实这个项目偏向于强制登录的，所有设置功能都是在登录的基础上

**Comment by UnknownErrorCodes** [comment]
> 也稍微改了下 下个版本试试吧。。。
> 
> 至于没登录的 完整配置发下，隐藏下自己的信息。。 另外其实这个项目偏向于强制登录的，所有设置功能都是在登录的基础上
完整docker-compose.yml配置如下
```
version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web:latest # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb2
    restart: unless-stopped
    ports:
      - '127.0.0.1:3004:3002'
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 二选一
      OPENAI_ACCESS_TOKEN: ''
      # 反向代理，可选
      API_REVERSE_PROXY: 'http://172.23.0.2:3000/backend-api/conversation'
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # 网站名称
      SITE_TITLE: ChatGpt Web
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt2:xxxx2@database:27017'
      # 网站是否开启注册
      REGISTER_ENABLED: false
    links:
      - database

  database:
    image: mongo
    container_name: chatgptweb-database2
    restart: unless-stopped
    ports:
      - '127.0.0.1:27018:27017'
    expose:
      - '27017'
    volumes:
      - mongodb2:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt2
      MONGO_INITDB_ROOT_PASSWORD: xxxx2
      MONGO_INITDB_DATABASE: chatgpt2

volumes:
  mongodb2: {}
networks:
  default:
    external:
      name: node-chatgpt-proxy_default
```
我是用v2ray配合修改hosts，直接访问服务器localhost:3004本身，所以该项目容器本身并不对外开放
由于只有我自己使用,开启登录功能反而不方便
