### ISSUE TITLE
部署后访问500 Server ERROR

### ISSUE THREAD

**Issue by 2ndelement** [Kerwin1202/chatgpt-web#370]
同样的配置文件在过去大概3个月运行都没有问题，但是停止之后重启出现问题。部署方式为使用Docker Compose，请问是我的compose配置文件问题吗，如下。
```yaml
version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: dasvg32423r53d
      # 网站名称
      SITE_TITLE: ChatGPT Web
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:17378222404@database:27017'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: aodjawio8328948drdfa
      # 开启注册之后 超级管理邮箱
      ROOT_USER: 2ndelementss@gmail.com
      # 网站是否开启注册 必须开启, 否则管理员都没法注册, 可后续关闭
      REGISTER_ENABLED: true
      # 更多配置, 在运行后, 注册管理员, 在管理员页面中设置
    links:
      - database

  database:
    image: mongo
    container_name: chatgptweb-database
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: 17378222404
      MONGO_INITDB_DATABASE: chatgpt

volumes:
  mongodb: {}⏎
```
