### ISSUE TITLE
[一键部署err] 使用docker-compose部署前端返回500

### ISSUE THREAD

**Issue by cffycls** [Kerwin1202/chatgpt-web#417]
```
version: '3'

services:
  app:
    # 在https://hub.docker.com/r/kerwin1202/chatgpt-web/tags 里获得tag。或者写latest
    image: kerwin1202/chatgpt-web:latest
    restart: unless-stopped
    ports:
      - 1004:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 从OpenAI后台里获得
      OPENAI_API_KEY: "sk-xxxxx" # 按需修改
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY: cls108 # 按需修改
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # 网站名
      SITE_TITLE: cffyChat # 按需修改。写个自己喜欢的名字就行
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://user01:password01@database:27017' # 按需修改
      # 网站是否开启注册
      REGISTER_ENABLED: true # 完成注册后，这一项要改为false
      # 开启注册之后 网站注册允许的邮箱后缀 如果空 则允许任意后缀
      REGISTER_MAILS: '@qq.com,@gmail.com,@163.com' # 按需修改
      # 加密盐。算法： echo -n 'passwordsalt' | md5sum | cut -c 1-32
      PASSWORD_MD5_SALT: tNJ%M&D # 按需修改
      # 开启注册之后 超级管理员的邮箱
      ROOT_USER: 724247159@qq.com # 按需修改
      # 开启注册之后网站域名 不含 / 。注册的时候发送验证邮箱使用
      # SITE_DOMAIN: https://172.16.0.114:8084 # 按需修改
      # 开启注册之后 发送验证邮箱配置
      # SMTP_HOST: smtp.qq.com
      # SMTP_PORT: 465
      # SMTP_TSL: true
      # SMTP_USERNAME: 724247159@qq.com # 按需修改
      # SMTP_PASSWORD: xxxxxxxx # 按需修改
    links:
      - database

  database:
    image: mongo:latest
    restart: unless-stopped
    expose:
      - '27017'
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user01
      MONGO_INITDB_ROOT_PASSWORD: password01
      MONGO_INITDB_DATABASE: chatgpt
```

使用docker-compose部署前端返回500
```
500
Server error
```
